#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

echo -e "⏳ Loading context data in \033[1mNGSI-LD\033[0m format"
echo -e "    - all entity data models are defined referencing the" 
echo -e "      \033[1m"${TUTORIAL_DATA_MODELS_CONTEXT}"\033[0m JSON-LD context"

# Create four Farm Entities in various locations across Berlin

curl -s -o /dev/null -X POST 'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entityOperations/upsert' \
-H 'Content-Type: application/json' \
-H 'Link: <'"${TUTORIAL_DATA_MODELS_CONTEXT}"'>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-H 'Accept: application/ld+json' \
--data-raw '[
  {
    "id": "urn:ngsi-ld:Building:farm001",
    "type": "Building",
    "category": {"type": "Property", "value": ["farm"]},
    "address": {
        "type": "Property",
        "value": { "streetAddress": "Großer Stern 1", "addressRegion": "Berlin", "addressLocality": "Tiergarten", "postalCode": "10557"},
        "verified": { "type": "Property", "value": true}
    },
    "location": {
        "type": "GeoProperty",
        "value": { "type": "Point", "coordinates": [13.3505, 52.5144]}
    },
    "name": {"type": "Property","value": "Victory Farm"},
    "owner": {"type": "Relationship", "object": "urn:ngsi-ld:Person:person001"}
  }
]'

echo -e " \033[1;32mdone\033[0m"